<?xml version="1.0"?>
<package format="3">
  <name>blind_locomotion</name>
  <version>1.0.0</version>
  <description>Python package for blind RL locomotion</description>
  <maintainer email="gabearod2@gmail.com">Gabriel_Rodriguez</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>sensor_msgs_py</depend>
  <depend>unitree_go</depend>
  <depend>unitree_api</depend>
  <depend>rosbag2_cpp</depend>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <build_depend>rosidl_default_generators</build_depend>
  <exec_depend>rosidl_default_runtime</exec_depend>

  <member_of_group>rosidl_interface_packages</member_of_group>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
